# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='actor',
        ),
        migrations.AddField(
            model_name='film',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='film',
            name='youtube',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='film',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
    ]
