# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_auto_20160312_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20)),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('photo', models.ImageField(blank=True, upload_to='actors')),
                ('description', models.TextField(blank=True)),
                ('film', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='films.Film')),
            ],
            options={
                'verbose_name': 'actor',
                'verbose_name_plural': 'actors',
                'ordering': ('name',),
            },
        ),
    ]
