# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='filmSlug',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
