# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-09 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_actor_filmslug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='film',
        ),
        migrations.AddField(
            model_name='actor',
            name='film',
            field=models.ManyToManyField(to='films.Film'),
        ),
    ]
